name: JoinEffect
main: YoungRichNigger9\Main
version: 1.0.0
api: [2.0.0]
author: YoungRichNigger9
description: Allows players to receive an effect when they join the server.
permissions:
    joineffect.cmd:
        default: false
        description: "Allow to receive the effect"
