
#Effect ID


# 1 - Speed
# 2 - Slowness
# 3 - Haste
# 4 - Mining Fatigue
# 5 - Strength
# 6 - Instant Health
# 7 - Instant Damage
# 8 - Jump Boost
# 9 - Nausea
# 10 - Regeneration
# 11 - Resistance
# 12 - Fire Resistance
# 13 - Water Breathing
# 14 - Invisibility
# 15 - Blindness
# 16 - Night Vision
# 17 - Hunger
# 18 - Weakness
# 19 - Poison
# 20 - Wither
# 21 - Health Boost
# 22 - Absorption
# 23 - Saturation 

#Important Note


#Effect-id: ID of the effect
#Effect-Duration in ticks: 1200 = 1 Minute | 20 = 1 second
#Amplifier = Power of the effect
#Particles: Show particles of the effect--> true / false


Effect-id: 1
Effect-Duration: 2400
Amplifier: 0
Particles: true
